# Generated by Django 4.2 on 2023-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
